version: '3.9'

services:
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
    - ./.docker/data:/var/lib/mysql
    env_file:
      - ./.env
    networks:
      - db-data
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    volumes:
      - ./:/app
    env_file:
      - ./.env
    depends_on:
      - db
    command: "npm run start:dev"
    networks:
      - db-data

volumes:
  db:
    name: nest-prisma-docker-db
  backend:
    name: nest-prisma

networks:
  db-data: